TravelBlogApp/Models/BlogItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TravelBlogApp.Models
{
    public class BlogItem
    {
        public BlogItem()
        {
            CreatedDate = DateTime.Now;
        }
        public int Id { get; set; }

        [Required(ErrorMessage = " Please enter a title for Blog ")]
        [MaxLength(200)]

        public string Title { get; set; }

        [MaxLength(10000)]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        [Display(Name = "Published")]
        public bool IsPublished { get; set; }

        [ScaffoldColumn(false)]
        public DateTime CreatedDate { get; set; }

        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }


          public string AuthorId { get; set; }

          public virtual Author Author { get; set; } 
    }
}

TravelBlogApp/Controllers/BlogItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TravelBlogApp.Data;
using TravelBlogApp.Models;

namespace TravelBlogApp.Controllers
{
    [Authorize]
    public class BlogItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Author> _userManager;

        public BlogItemsController(ApplicationDbContext context, UserManager<Author> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: BlogItems
        public async Task<IActionResult> Index(SearchViewModel searchViewModel)
        {
            var author = await _userManager.GetUserAsync(HttpContext.User);
            var query = _context.BlogItems
                .Include(b => b.Category).Where(t=>t.AuthorId==author.Id).AsQueryable();
                
            if (!String.IsNullOrWhiteSpace(searchViewModel.SearchText))
            {
                query = query.Where(t => t.Title.Contains(searchViewModel.SearchText ));
            }
            
            query=query.OrderByDescending(t => t.CreatedDate);

            searchViewModel.Result = await query.ToListAsync();

            return View(searchViewModel);
        }

        // GET: BlogItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogItem = await _context.BlogItems
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            var author = await _userManager.GetUserAsync(HttpContext.User);
            if (blogItem.AuthorId != author.Id)
            {
                return Unauthorized();
            }
            if (blogItem == null)
            {
                return NotFound();
            }

            return View(blogItem);
        }

        // GET: BlogItems/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.CategorySelectList = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        // POST: BlogItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,IsPublished,CategoryId")] BlogItem blogItem)
        {
            var author = await _userManager.GetUserAsync(HttpContext.User);

            blogItem.AuthorId = author.Id;

            if (ModelState.IsValid)
            {
                _context.Add(blogItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogItem.CategoryId);
            return View(blogItem);
        }

        // GET: BlogItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogItem = await _context.BlogItems.FindAsync(id);
            var author = await _userManager.GetUserAsync(HttpContext.User);
            if (blogItem.AuthorId != author.Id)
            {
                return Unauthorized();
            }
            if (blogItem == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogItem.CategoryId);
            return View(blogItem);
        }

        // POST: BlogItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,IsPublished,CategoryId,CreatedDate,AuthorId")] BlogItem blogItem)
        {
            if (id != blogItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var oldBlog = await _context.BlogItems.FindAsync(id);
                    var author = await _userManager.GetUserAsync(HttpContext.User);
                    if (oldBlog.AuthorId != author.Id)
                    {
                        return Unauthorized();
                    }
                    oldBlog.Title = blogItem.Title;
                    oldBlog.CreatedDate = blogItem.CreatedDate;
                    oldBlog.Content = blogItem.Content;
                    oldBlog.IsPublished = blogItem.IsPublished;
                    oldBlog.CategoryId = blogItem.CategoryId;

                    _context.Update(oldBlog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogItemExists(blogItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogItem.CategoryId);
            return View(blogItem);
        }

        // GET: BlogItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogItem = await _context.BlogItems
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            var author = await _userManager.GetUserAsync(HttpContext.User);
            if (blogItem.AuthorId != author.Id)
            {
                return Unauthorized();
            }
            if (blogItem == null)
            {
                return NotFound();
            }

            return View(blogItem);
        }

        // POST: BlogItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogItem = await _context.BlogItems.FindAsync(id);
            _context.BlogItems.Remove(blogItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        

        private async Task<ActionResult> ChangeStatus(int id,bool status)
        {
            var blogItemItem = _context.BlogItems.FirstOrDefault(t => t.Id == id);
            if (blogItemItem == null)
            {
                return NotFound();
            }
            blogItemItem.IsPublished = status;


            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<ActionResult> Publish(int id)
        {
            return await ChangeStatus(id, true);
        }
        public async Task<ActionResult> UndoPublish(int id)
        {
            return await ChangeStatus(id, false);
        }

        private bool BlogItemExists(int id)
        {
            return _context.BlogItems.Any(e => e.Id == id);
        }
    }
}

TravelBlogApp/Views/BlogItems/Create.cshtml
@model TravelBlogApp.Models.BlogItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>New Blog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPublished" /> @Html.DisplayNameFor(model => model.IsPublished)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category Name</label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategorySelectList"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" style=" color:goldenrod ">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TravelBlogApp/Views/BlogItems/Delete.cshtml
@model TravelBlogApp.Models.BlogItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
  
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete" style=" color:goldenrod ">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" style=" color:goldenrod ">Back to List</a>
    </form>
</div>

TravelBlogApp/Views/BlogItems/Details.cshtml
@model TravelBlogApp.Models.BlogItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" style=" color:goldenrod ">Edit</a> |
    <a asp-action="Index" style=" color:goldenrod ">Back to List</a>
</div>

TravelBlogApp/Views/BlogItems/Edit.cshtml
@model TravelBlogApp.Models.BlogItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPublished" /> @Html.DisplayNameFor(model => model.IsPublished)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category Name</label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
            
                <input asp-for="CreatedDate" type="hidden" class="form-control" />
                <input asp-for="AuthorId" type="hidden" class="form-control" />
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" style=" color:goldenrod ">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TravelBlogApp/Views/BlogItems/Index.cshtml
@model SearchViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>My Blogs</h1>

<p>
    <a asp-action="Create" style=" color:goldenrod ">Add a New Post</a>
</p>

<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" asp-action="Index" asp-controller="BlogItems" method="get" >
    <div class="input-group">
        <input asp-for="SearchText" name="SearchText" id="SearchText" class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
        <button class="btn btn-secondary" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
    </div>
</form>
<table class="table" style="margin-top:50px">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Category
            </th>
            <th>
                CreatedDate
            </th>
            <th>
                IsPublished
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Result)
        {
            <tr>
                <td>
                    @if (item.IsPublished)
                    {
                        <span style="COLOR: green">@Html.DisplayFor(modelItem => item.Title)</span>
                    }
                    else
                    {
                        <span style="COLOR: red">@Html.DisplayFor(modelItem => item.Title)</span>
                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>

                    @Html.DisplayFor(modelItem => item.IsPublished)
                </td>

                <td>
                    @if (item.IsPublished)
                    {
                        <a asp-action="UndoPublish" asp-route-id="@item.Id" style=" color:goldenrod ">Undo Publish</a>
                    }
                    else
                    {
                        <a asp-action="Publish" asp-route-id="@item.Id" style=" color:goldenrod ">Publish</a>
                    }

                    | <a asp-action="Edit" asp-route-id="@item.Id" style=" color:goldenrod ">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" style=" color:goldenrod ">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" style=" color:goldenrod ">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>